pipeline:
  identifier: Build_tfdemo_1689833180569
  name: Build tfdemo
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github
        repoName: satishcloudsec/tfdemo
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Security Scan TF
                  identifier: Security_Scan_TF
                  spec:
                    connectorRef: account.harnessImage
                    image: bridgecrew/checkov
                    shell: Sh
                    command: checkov -d .
              - step:
                  identifier: echo
                  name: Terraform
                  spec:
                    connectorRef: account.harnessImage
                    image: hashicorp/terraform
                    shell: Sh
                    command: |-
                      echo "Terraform Init"
                      terraform init
                      echo "Tearraform Plan"
                      terraform plan
                    envVariables:
                      TF_VAR_accesskey: <+secrets.getValue("accesskey")>
                      TF_VAR_secretkey: <+secrets.getValue("AWS_Secret_Access_Key")>
                  timeout: ""
                  type: Run
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
